kind: "Site"
apis:
  - "asset"
  - "com.enonic.app.features:sse"
  - "com.enonic.app.features:websocket"
  - "com.enonic.app.features:websocket-public"
  - "com.enonic.app.features:cron"
  - "com.enonic.app.features:cron-sse"
  - "com.enonic.app.features:cron-ws"
processors:
  - name: "bgcolor-filter"
    order: 10
  - name: "branch-filter"
    order: 10
  - name: "app-header-filter"
    order: 10
  - name: "custom-attributes-processor"
    order: 20
  - name: "csp-processor"
    order: 20
mappings:
  - controller: "/services/cors/cors.js"
    order: 40
    invertPattern: false
    pattern: "/cors-demo"
  - controller: "/cms/mappings/controller.js"
    order: 50
    invertPattern: false
    pattern: "/controller"
  - controller: "/cms/mappings/sse-controller.js"
    order: 50
    invertPattern: false
    pattern: "/sse-mapping"
  - filter: "/cms/mappings/filter1.js"
    order: 50
    invertPattern: false
    pattern: "/filter1"
  - filter: "/cms/mappings/filter2.js"
    order: 50
    invertPattern: false
    pattern: "/"
  - filter: "/cms/mappings/reroute-filter.js"
    order: 50
    invertPattern: false
    pattern: "/request-steering"
  - filter: "/cms/mappings/custom-attributes-filter.js"
    order: 50
    invertPattern: false
    pattern: "/custom-attributes"
  - controller: "/cms/mappings/schedule-types/schedule-types.js"
    order: 50
    invertPattern: false
    pattern: "/schedule-types"
  - controller: "/cms/mappings/libraries/index.js"
    order: 50
    invertPattern: false
    pattern: "/libraries"
  - controller: "/cms/mappings/libraries/cluster/cluster.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/cluster"
  - controller: "/cms/mappings/libraries/content/content.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/content"
  - controller: "/cms/mappings/libraries/context/context.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/context"
  - controller: "/cms/mappings/libraries/i18n/i18n.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/i18n"
  - controller: "/cms/mappings/libraries/node/node.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/node"
  - controller: "/cms/mappings/libraries/repo/repo.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/repo"
  - controller: "/cms/mappings/libraries/value/value.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/value"
  - controller: "/cms/mappings/libraries/get-context/get-context.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/get-context"
  - controller: "/cms/mappings/libraries/markdown/markdown.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/markdown"
  - controller: "/cms/mappings/libraries/sql/sql.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/sql"
  - controller: "/cms/mappings/libraries/xslt/xslt.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/xslt"
  - controller: "/cms/mappings/libraries/auditlog/auditlog.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/auditlog"
  - controller: "/cms/mappings/libraries/auth/auth.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/auth"
  - controller: "/cms/mappings/libraries/cache/cache.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/cache"
  - controller: "/cms/mappings/libraries/http/http.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/http"
  - controller: "/cms/mappings/libraries/memberships/memberships.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/memberships"
  - controller: "/cms/mappings/libraries/move-content/move-content.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/move-content"
  - controller: "/cms/mappings/libraries/notifications/notifications.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/notifications"
  - controller: "/cms/mappings/libraries/publish/publish.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/publish"
  - controller: "/cms/mappings/libraries/qrcode/qrcode.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/qrcode"
  - controller: "/cms/mappings/libraries/sanitize/sanitize.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/sanitize"
  - controller: "/cms/mappings/libraries/scheduler/scheduler.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/scheduler"
  - controller: "/cms/mappings/libraries/unpublish/unpublish.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/unpublish"
  - controller: "/cms/mappings/libraries/node-listing/node-listing.js"
    order: 50
    invertPattern: false
    pattern: "/libraries/node-listing"
  - controller: "/cms/mappings/samples/sorting/sorting.js"
    order: 50
    invertPattern: false
    pattern: "/samples/sorting"
  - controller: "/cms/mappings/samples/date-and-time/date-and-time.js"
    order: 50
    invertPattern: false
    pattern: "/samples/form-items/date-and-time"
  - controller: "/cms/mappings/samples/media/media.js"
    order: 50
    invertPattern: false
    pattern: "/samples/media"
  - controller: "/cms/mappings/samples/attachments/attachments.js"
    order: 50
    invertPattern: false
    pattern: "/samples/my-attachment-content"
