name: Gradle Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: enonic/release-tools/build-and-publish@master

  release:
    runs-on: ubuntu-latest

    needs: build
    if: needs.build.outputs.release == 'true'

    steps:
      - uses: enonic/release-tools/release@master